### ISSUE TITLE
How do you add gaussian noise to categorical features

### ISSUE THREAD

**Issue by VCCIV** [AstraZeneca/SubTab#10]
I find that you use onehot_encoder to process categorical features.  However, one feature after onehot become to [ 0,xxx,0,1,0,xxx,0]. Do you add gaussian noise to all elements?  I'm not clear on how you do it here.

**Comment by talipucar** [comment]
We treat all features (continuous and categorical) similarly although you can choose to treat them differently. One of the main assumptions made in the paper is that we don't make any assumptions about the underlying features / data.

Moreover, adding gaussian noise to one-hot encoded features is no different than adding gaussian noise to MNIST, or any other binarised sparse dataset. But, again, you can choose to add different type of noise to categorical and continuous features if you want. For example, one can choose to use swap-noise for categorical features, and gaussian noise for continuous ones. In this case, please keep in mind that if the categorical features are very sparse, using something like swap-noise may not help much. 

I hope that this helps. I will close the issue, but if your question is not answered, please feel free to re-open it.
