### ISSUE TITLE
Package version conflict in requirements.txt

### ISSUE THREAD

**Issue by wwweiwei** [AstraZeneca/SubTab#14]
Thanks a lot for open source the code of this paper. It's really interesting!
I encountered a problem when installing the packages by requirements.txt.

> ERROR: Cannot install -r requirements.txt (line 2) and chardet==4.0.0 because these package versions have conflicting dependencies.
> 
> The conflict is caused by:
>     The user requested chardet==4.0.0
>     aiohttp 3.7.3 depends on chardet<4.0 and >=2.0

My python version is 3.7.1. Had anyone had fixed this conflict before? Thank you.

**Comment by talipucar** [comment]
Hi Wei-Wei,

As suggested in the README file, please use the following command when installing packages:

`pipenv install --skip-lock
`

Using "--skip-lock" option should resolve this issue. Pipenv is not good at backtracking to resolve dependency conflicts. 
I will close this issue, but please feel free to reopen it if the suggestion does not work.

**Comment by wwweiwei** [comment]
I've got it. Thank you so much!
