### ISSUE TITLE
swap noise, encoding and loss related to implementation

### ISSUE THREAD

**Issue by mortezamg63** [AstraZeneca/SubTab#15]
For tabular datasets containing categorical features, do you use swap noise and subset selection before one-hot encoding? Do you do swap noise before one-hot encoding as well?
Do you use different losses for categorical, numerical, and binary features? what about activation functions? is it different activation functions for different feature types?

Recent papers/works that apply self-supervised and semi-supervised settings to the tabular datasets, just have shared code for MNIST dataset. No one shares the code for tabular datasets. Could you please share your code for just one dataset containing categorical, numerical features?

**Comment by talipucar** [comment]
Hi Morteza,

I think that the answers to the most of your questions are already in the paper and in its appendix. However, I will give a short answer here:

Once the categorical data is one-hot encoded, there is no special treatment of them. They are combined with continuous features, and we treat all features in the same way, whether it is adding a particular noise to them, or dividing them into subsets.

Regarding the code for tabular data, adding new datasets is really easy and is already described in README in details. For example, if you preprocess and split Income dataset into training and test sets, all you have to do is to include following loading function in load_data.py file as described in README file:

```
def _load_income(self):

        x_train = np.load("./data/income/train_features.npy")
        y_train = np.load("./data/income/train_label.npy")
        x_test = np.load("./data/income/test_features.npy")
        y_test = np.load("./data/income/test_label.npy")
       
        return x_train, y_train, x_test, y_test
```

I will close this issue. However, if you have any further specific questions regarding preprocessed tabular datasets, please send me an email at ucabtuc@gmail.com .

**Comment by mortezamg63** [comment]
Thank you very much Talip. Sure. I did some experiments on your code on the Income dataset. I have some questions. I will send you an email.
Thanks for the quick reply.
