### ISSUE TITLE
Suitable for Regression?

### ISSUE THREAD

**Issue by rongliangzi** [AstraZeneca/SubTab#16]
The pretraining process doesn't use label information, so I guess SubTab also apply for regression like classification? Or anywhere needs to be modified?

**Comment by talipucar** [comment]
Yes, it is suitable for classification / regression. You can either 

1- Attach a network (e.g., Classifier) to the middle of encoder-decoder to train it with supervised loss. 

2-Or you can remove the decoder, and just train classifier with supervised loss directly. Basically, you can choose not to use contrastive or reconstruction losses, completely up to you.

In this case, what you use as input to the classifier is again your choice. For example, you can first get the joint embedding and use it as input to the classifier. Or, you can use the embedding of each subset to get a prediction from each, and then do a majority vote among them (or take their average).

I will close the issue, but if you have more questions, please feel free to re-open it.
