### ISSUE TITLE
Other datasets

### ISSUE THREAD

**Issue by zhenye234** [AstraZeneca/SubTab#9]
Will you provide code for other datasets in your paper( Income Blog Obesity TCGA) in the future?

**Comment by talipucar** [comment]
To keep the repo uncluttered and clean, there is no plan to add any code for additional datasets. We want users to have a clean starting code for their own use cases. 

The Blog, Income etc. datasets are publicly available, and it should be relatively easy to add additional load function for each dataset as described in the README file. The function needs to return training and test splits at the end, e.g., :

`    def _load_blog(self):
        .....
        return x_train, y_train, x_test, y_test
`

I hope that this helps. I will close this issue, but please feel free to re-open it, or send me an email if you have a specific question(s) at ucabtuc@gmail.com .
